FROM lambgeo/lambda-gdal:3.2-python3.8

RUN pip install pandas
RUN pip install geopandas
RUN pip install rasterio
RUN pip install mercantile 
RUN pip install click
RUN pip install shapely
RUN pip install geojson
RUN pip install tqdm
RUN pip install smart_open[s3]
RUN pip install pyproj

WORKDIR /mnt